# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ENGS31LAB5/lab5-17X.xdc

# IP: ip/Chinese_music/Chinese_music.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Chinese_music || ORIG_REF_NAME==Chinese_music} -quiet] -quiet
